<?php

use Drupal\Core\Database\Database;
use Drupal\Core\Path\AliasStorageInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Menu\MenuLinkTreeInterface;

/**
 * Implements hook_install().
 */
function rep_install() {
  // Define the schema for user_tracking table.
  $schema['user_tracking'] = [
    'description' => 'Stores user session history',
    'fields' => [
      'uid' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'User ID',
      ],
      'previous_url' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Previous URL',
      ],
      'current_url' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Current URL',
      ],
      'created' => [
        'type' => 'int',
        'not null' => TRUE,
        'description' => 'Timestamp when the entry was created',
      ],
    ],
    'primary key' => ['uid', 'current_url'],
  ];

  // Create the table.
  Database::getConnection()->schema()->createTable('user_tracking', $schema['user_tracking']);
}

/**
 * Implements hook_form_alter().
 */
function rep_form_alter(&$form, &$form_state, $form_id) {
  // Check if the form ID matches your configuration form.
  if ($form_id == 'rep_form_namespace' ||
      $form_id == 'rep_form_preferred_names' ||
      $form_id == 'rep_form_update_namespace') {
      // Remove the default "Save configuration" button.
    unset($form['actions']['submit']);
  }
}

/**
 * Implements hook_menu_alter().
 */
/*
function rep_menu_alter(&$items) {
  // Change the title of the menu item with path 'node/1/edit'.
  if (isset($items['node/1/edit'])) {
    $items['node/1/edit']['title'] = 'Edit Article';
  }
}
*/

/**
 * Implements hook_theme
 */
function rep_theme($existing, $type, $theme, $path)
{
    return [
        'list-page' => [
            'variables' => array(
                'items' => array(
                    'offset' => '',
                    'first' => '',
                    'last' => '',
                    'previous' => '',
                    'next' => '',
                    'links' => array(),
                    'title' => ''
                )
            )
        ],
    ];
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function rep_preprocess_block(&$variables) {
  // Add the core/drupal.dialog.ajax library.
  $variables['#attached']['library'][] = 'core/drupal.dialog.ajax';
  $attachments['#attached']['library'][] = 'rep/rep_js_css';
}

/**
 * Implements hook_help().
 */
function rep_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'rep.help':
        return '<h2>This is the help content for the HAScO Semantics Package.</h2>';
    }
  }

/**
 * Implements hook_update_N().
 */
function rep_update_8001() {

  \Drupal::configFactory()->getEditable('system.site')->set('page.front', '/rep/list/instrument/_/_/1/12')->save();

}

/**
 * Implementa hook_menu_links_discovered_alter().
 */
function rep_menu_links_discovered_alter(&$links) {
  $target_links = [
    'reviewer.top_level',
    'reviewer.response_options',
  ];

  foreach ($target_links as $link_key) {
    if (isset($links[$link_key])) {
      // Define o requisito de acesso personalizado.
      $links[$link_key]['requirements']['_custom_access_check'] = 'TRUE';
    }
  }

  $config = \Drupal::config('rep.settings');
  $sagres_enabled = $config->get('sagres_conf');
  \Drupal::logger('rep')->notice('sagres_conf: ' . $form_state->getValue('sagres_conf'));


  if ($sagres_enabled == 0) {
    $to_hide = [
      'rep.sagres',
      'rep.sagres_config',
      'rep.sagres_status',
    ];

    foreach ($links as $key => $link) {
      if ((isset($link['route_name']) && in_array($link['route_name'], [
              'rep.sagres.status_form',
              'rep.sagres.config_form'
          ])) || in_array($key, $to_hide)) {
          unset($links[$key]);
      }
    }
  }
}

/**
 * Função de callback de acesso personalizada.
 *
 * @param \Drupal\Core\Session\AccountInterface $account
 *   A conta do usuário.
 *
 * @return \Drupal\Core\Access\AccessResultInterface
 *   O resultado do acesso.
 */
function rep_custom_access_callback(AccountInterface $account) {
  // Verifica se o utilizador possui o papel 'content_editor'.
  $has_content_editor = $account->hasRole('content_editor');

  // Verifica se o utilizador NÃO possui o papel 'administrator'.
  $is_not_administrator = !$account->hasRole('administrator');

  if ($has_content_editor && $is_not_administrator) {
    return AccessResult::allowed()->cachePerUser();
  }

  return AccessResult::forbidden()->cachePerUser();
}

/**
 * Implementa hook_user_insert().
 * É chamado quando um novo usuário é criado no Drupal.
 */
function rep_user_insert($account) {

  $sagres_token = \Drupal::service('request_stack')->getCurrentRequest()->getSession()->get('oauth_access_token');
  
  if (!$sagres_token) {
    \Drupal::logger('rep')->error("Token não encontrado na sessão.");
    return;
  }

  $json_data = json_encode([
    'acc_id' => $account->id(),
    'acc_repo_instance' => \Drupal::request()->getHost(),
    'acc_name' => $account->getDisplayName(),
    'acc_email' => $account->getEmail(),
    'acc_user_uri' => \Drupal::request()->getSchemeAndHttpHost() . '/user/' . $account->id(),
  ]);

  try {
    $response = \Drupal::httpClient()->post('http://192.168.1.73/sguser/account/add', [
      'headers' => [
        'Content-Type' => 'application/json',
        'Authorization' => "Bearer {$sagres_token}",
      ],
      'body' => $json_data,
    ]);

    if ($response->getStatusCode() == 201) {
      \Drupal::logger('rep')->notice("Conta {$account->id()} enviada para sguser.");
    }
  } catch (RequestException $e) {
    \Drupal::logger('rep')->error("Erro ao enviar conta {$account->id()} para sguser: " . $e->getMessage());
  }
}

/**
 * Implementa hook_user_update().
 * É chamado quando um usuário é atualizado no Drupal.
 */
function rep_user_update($account) {

  $sagres_token = \Drupal::service('request_stack')->getCurrentRequest()->getSession()->get('oauth_access_token');

  if (!$sagres_token) {
    \Drupal::logger('rep')->error("Token não encontrado na sessão.");
    return;
  }

  $json_data = json_encode([
    'acc_id' => $account->id(),
    'acc_repo_instance' => \Drupal::request()->getHost(),
    'acc_name' => $account->getDisplayName(),
    'acc_email' => $account->getEmail(),
    'acc_user_uri' => \Drupal::request()->getSchemeAndHttpHost() . '/user/' . $account->id(),
  ]);

  try {
    $response = \Drupal::httpClient()->post('http://192.168.1.73/sguser/account/update', [
      'headers' => [
        'Content-Type' => 'application/json',
        'Authorization' => "Bearer {$sagres_token}", // Adicionando o token aqui
      ],
      'body' => $json_data,
    ]);

    if ($response->getStatusCode() == 200) {
      \Drupal::logger('rep')->notice("Conta {$account->id()} atualizada no sguser.");
    }
  } catch (RequestException $e) {
    \Drupal::logger('rep')->error("Erro ao atualizar conta {$account->id()} no sguser: " . $e->getMessage());
  }
}

/**
 * Implementa hook_user_delete().
 * É chamado quando um usuário é removido no Drupal.
 */
function rep_user_delete($account) {

  $sagres_token = \Drupal::service('request_stack')->getCurrentRequest()->getSession()->get('oauth_access_token');

  if (!$sagres_token) {
    \Drupal::logger('rep')->error("Token não encontrado na sessão.");
    return;
  }

  $acc_repo_instance = \Drupal::request()->getHost();

  $url = 'http://192.168.1.73/sguser/account/delete/' . $account->id() . '/' . $acc_repo_instance;

  try {
    $response = \Drupal::httpClient()->delete($url, [
      'headers' => [
        'Authorization' => "Bearer {$sagres_token}",
      ],
    ]);

    if ($response->getStatusCode() == 200) {
      \Drupal::logger('rep')->notice("Conta {$account->id()} removida do sguser.");
    }
  } catch (RequestException $e) {
    \Drupal::logger('rep')->error("Erro ao remover conta {$account->id()} do sguser: " . $e->getMessage());
  }
}