<?php

  namespace Drupal\rep;

  use Drupal\rep\Vocabulary\HASCO;

  class EntryPoints {

    // CLASSES
    const CLASS_EP_ANNOTATION_STEM           = HASCO::ANNOTATION_STEM_CLASS_ENTRY_POINT;
    const CLASS_EP_ATTRIBUTE                 = HASCO::ATTRIBUTE_CLASS_ENTRY_POINT;
    const CLASS_EP_CODEBOOK                  = HASCO::CODEBOOK_CLASS_ENTRY_POINT;
    const CLASS_EP_COMPONENT_STEM            = HASCO::COMPONENT_STEM_CLASS_ENTRY_POINT;
    const CLASS_EP_COMPONENT                 = HASCO::COMPONENT_CLASS_ENTRY_POINT;
    const CLASS_EP_COMPONENT_ATTRIBUTE       = HASCO::COMPONENT_ATTRIBUTE_CLASS_ENTRY_POINT;
    const CLASS_EP_ENTITY                    = HASCO::ENTITY_CLASS_ENTRY_POINT;
    const CLASS_EP_GROUP                     = HASCO::GROUP_CLASS_ENTRY_POINT;
    const CLASS_EP_INSTRUMENT                = HASCO::INSTRUMENT_CLASS_ENTRY_POINT;
    const CLASS_EP_ORGANIZATION              = HASCO::ORGANIZATION_CLASS_ENTRY_POINT;
    const CLASS_EP_PERSON                    = HASCO::PERSON_CLASS_ENTRY_POINT;
    const CLASS_EP_PLACE                     = HASCO::PLACE_CLASS_ENTRY_POINT;
    const CLASS_EP_WORKFLOW_STEM             = HASCO::WORKFLOW_STEM_CLASS_ENTRY_POINT;
    // const EP_QUESTIONNAIRE             = HASCO::QUESTIONNAIRE_ENTRY_POINT;
    const CLASS_EP_RESPONSE_OPTION           = HASCO::RESPONSE_OPTION_CLASS_ENTRY_POINT;
    const CLASS_EP_STUDY                     = HASCO::STUDY_CLASS_ENTRY_POINT;
    const CLASS_EP_TASK                      = HASCO::TASK_CLASS_ENTRY_POINT;
    const CLASS_EP_TASK_TEMPORAL_DEPENDENCY  = HASCO::TASK_TEMPORAL_DEPENDENCY_CLASS_ENTRY_POINT;


    // INSTANCES
    const INSTANCE_EP_INSTRUMENT             = HASCO::INSTRUMENT_INSTANCE_ENTRY_POINT;
    const INSTANCE_EP_COMPONENT              = HASCO::COMPONENT_INSTANCE_ENTRY_POINT;
    const INSTANCE_EP_PLATFORM               = HASCO::PLATFORM_INSTANCE_ENTRY_POINT;
    const INSTANCE_EP_UNIT                   = HASCO::UNIT_INSTANCE_ENTRY_POINT;

  }
