<?php

namespace Drupal\rep;

use Drupal\rep\Utils;
use Drupal\rep\Entity\Tables;

class ListDerivation {

  public static function exec($uri) {
    if ($uri == NULL) {
        $resp = array();
        return $resp;
    }
    $api = \Drupal::service('rep.api_connector');
    $elements = $api->parseObjectResponse($api->getDerivation($uri), 'getDerivation');
    if ($elements == NULL) {
      $elements = array();
      return $elements;
    }
    //$elements = array();
    return $elements;
  }

  public static function fromComponentToHtml($components) {
    $tables = new Tables;
    $generationActivities = $tables->getGenerationActivities();
    $html = "<ul>";
    if (sizeof($components) <= 0) {
      $html .= "<li>NONE</li>";
    } else {
      foreach ($components as $component) {
        if ($component != NULL) {
          $content = "(EMPTY)";
          $generation = "(UNKNOWN)";
          if ($component->hasContent != NULL && $component->hasContent != "") {
            $content = $component->hasContent;
          }
          if ($component->wasGeneratedBy != NULL && $component->wasGeneratedBy != "") {
            $generation = $generationActivities[$component->wasGeneratedBy];
          }
          $html .= "<li>Component " . Utils::repUriLink($component->uri) . " (" . $content . ") generated by " . $generation . "</li>";
        }
      }
    }
    $html .= "</ul>";
    return $html;
  }

}

?>
