name: Run Selenium Tests

on:
  push:
    branches:
      - stream_topics

jobs:
  run-selenium-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          chromium-browser --version
          chromedriver --version

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          sleep 3

      - name: Compile all Java test files
        run: |
          find tests/A1 -name "*.java" > sources.txt
          LIBS=$(find tests/selenium-java-4.26.0 -name "*.jar" | tr '\n' ':')
          CLASSPATH=".:${LIBS}tests/junit-platform-console-standalone-1.8.2.jar"
          javac -cp "$CLASSPATH" @sources.txt

      - name: Wait for hascogui to be ready
        run: |
          until curl -s http://localhost:80/ > /dev/null; do
            echo "Waiting for hascogui environment to start..."
            sleep 5
          done

      - name: Run Regression Test
        run: |
          LIBS=$(find tests/selenium-java-4.26.0 -name "*.jar" | tr '\n' ':')
          CLASSPATH=".:${LIBS}tests/junit-platform-console-standalone-1.8.2.jar:tests"
          java -cp "$CLASSPATH" org.junit.platform.console.ConsoleLauncher --select-class "tests.A1.RegressionTEST"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const message = `❌ The tests have failed! @${prAuthor}, please check the logs and fix the problems before merging.`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            })

      - name: Notify via Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ The tests for the PR #${{ github.event.pull_request.number }} have failed. Author: @${{ github.event.pull_request.user.login }}. Check the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ The tests for the PR #${{ github.event.pull_request.number }} have passed! Author: @${{ github.event.pull_request.user.login }}. Check the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
