name: Run Selenium Tests

on:
  push:
    branches:
      - test_process_kael

jobs:
  run-selenium-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install unzip
        run: sudo apt-get install -y unzip
      - name: Install Chrome 125 manually
        run: |
          wget -q https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chrome-linux64.zip
          unzip -q chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -sf /opt/chrome/chrome /usr/bin/google-chrome


      - name: Install ChromeDriver manually into /usr/bin
        run: |
          wget -q https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip
          unzip -q chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          rm -rf chromedriver-linux64.zip chromedriver-linux64
        shell: bash
      - name: Set DISPLAY variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          sleep 3

      - name: Compile all Java test files
        run: |
          find tests/A1 -name "*.java" > sources.txt
          LIBS=$(find tests/selenium-java-4.26.0 -name "*.jar" | tr '\n' ':')
          CLASSPATH=".:${LIBS}tests/junit-platform-console-standalone-1.8.2.jar"
          javac -cp "$CLASSPATH" @sources.txt

      - name: Wait for hascogui to be ready
        run: |
          until curl -s http://18.203.69.17:80/ > /dev/null; do
            echo "Waiting for hascogui environment to start..."
            sleep 5
          done

      - name: Run Regression Test
        run: |
          LIBS=$(find tests/selenium-java-4.26.0 -name "*.jar" | tr '\n' ':')
          CLASSPATH=".:${LIBS}tests/junit-platform-console-standalone-1.8.2.jar:tests"
          java -cp "$CLASSPATH" org.junit.platform.console.ConsoleLauncher --select-class "tests.A1.RegressionTEST"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const message = `❌ The tests have failed! @${prAuthor}, please check the logs and fix the problems before merging.`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            })

      - name: Notify via Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ The tests for the PR #${{ github.event.pull_request.number }} have failed. Author: @${{ github.event.pull_request.user.login }}. Check the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ The tests for the PR #${{ github.event.pull_request.number }} have passed! Author: @${{ github.event.pull_request.user.login }}. Check the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
